### ISSUE TITLE
Acceso a postgresql

### ISSUE THREAD

**Issue by jicelhay** [IIC2513-2015-1/syllabus#10]
Hola, instale la version 9.4 de psql. Al momento de instalarla pide una pass para el super usuario.
Cuando intento acceder a la consola psql para crear el rol de la app me pide la contraseña, y no hay forma de que me acepte. me tira: psql: FATAL: Password authentication failed for user “postgres”
He intentado desinstalarla y cambiar el pass un par de veces pero nada.
Alguien le pasa lo mismo? Como lo soluciono? Saludos (estoy en windows).

**Comment by lopezjurip** [comment]
Suele pasar, revisa:
http://stackoverflow.com/questions/18698889/postgresql-windows-is-there-a-default-password

**Comment by jicelhay** [comment]
buena! lo pude resolver con esto por si a alguien le pasa:
http://stackoverflow.com/questions/6216432/windows-psql-command-line-is-there-a-way-to-allow-for-passwordless-login
