### ISSUE TITLE
Duda entrega 1 - show.hml (sic)

### ISSUE THREAD

**Issue by jecastro1** [IIC2513-2015-1/syllabus#13]
Hola, 

Espero no se burlen con mi pregunta jaja. Entiendo la intuición de lo que debería colocar en `index.html`, pero no así con `show.hml` (sic).

¿Es una página por modelo? ¿Es para la página completa? ¿Que se espera ahí? Gracias

**Comment by lopezjurip** [comment]
Sea el modelo `Users`. 

Al ingresar a `miapp.cl/users` se ejecuta el método `index` del `controllers/users_controller.rb` y toma la vista `views/users/index.html.erb` para generar la página `html`. (por defecto, a menos que se quiera renderizar otra vista).

Al ingresar a `miapp.cl/users/42`, se ejecuta el método `show` del `controllers/users_controller.rb` y toma la vista `views/users/show.html.erb` para generar la página `html`. En este caso, la _url_ viene con el parámetro `:id` que puedes usar para conseguir al usuario con esa _id_. Por ejemplo: 

``` ruby
def show
  @user = User.find_by_id(params[:id])
end
```

Entonces al renderizar la vista `show.html.erb`, dispondrás de la instancia `@user` para conseguir el `id`, `nombre`, `edad`, etc y ejecutar cualquier método de una instancia de `User`.

También puedes por ejemplo renderizar otra página si tal `id` no existe:

``` ruby
def show
  @user = User.find_by_id(params[:id])
  render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found unless @user.present?
end
```

**Comment by jecastro1** [comment]
Muchas gracias

**Comment by lopezjurip** [comment]
**EDIT:**
Aunque la implementación correcta de chequear si tal usuario con `id` existe es con un `before_action:` :

``` ruby
class UsersController < ApplicationController
  before_action :set_user!, only: [:show, :edit, :update, :destroy]

  def show
  end

  # ...

  def set_user!  # Se usa con ! para indicar que este método puede renderizar otro archivo en caso de fallo
    @user = User.find_by_id(params[:id])
    render :file => "#{Rails.root}/public/404", :layout => false, :status => :not_found unless @user.present?
  end
end
```
