### ISSUE TITLE
pg search

### ISSUE THREAD

**Issue by vdrg** [IIC2513-2015-1/syllabus#16]
Podemos usar la gema pg search? O alguna otra gema para búsqueda?

Gracias!

**Comment by vdrg** [comment]
Y lo otro, para el mapa podemos ocupar google-maps-for-rails? Gracias

**Comment by lopezjurip** [comment]
Disculpen, no había visto la primera pregunta.

Sobre Google maps, sí, úsenla, la van a necesitar para su proyecto :+1: 
Sobre _pg search_, yo diría que sí

**Comment by vdrg** [comment]
Gracias!
