### ISSUE TITLE
Client Side Validations

### ISSUE THREAD

**Issue by jecastro1** [IIC2513-2015-1/syllabus#24]
Hola, 

Se puede utilizar [client_side_validations](https://github.com/DavyJonesLocker/client_side_validations) para hacer la validación de los formularios? O alguna similar?

**Comment by lopezjurip** [comment]
Diría que no, la idea es que las hagan a mano con JS

**Comment by jecastro1** [comment]
Dale, tampoco [este plugin de jQuery](http://jqueryvalidation.org/) ?

**Comment by lopezjurip** [comment]
Yo creo que es complicarse de más, pero úsalo si quieres.

**Comment by jecastro1** [comment]
vale gracias
