### ISSUE TITLE
Mejor forma de consumir una API

### ISSUE THREAD

**Issue by jecastro1** [IIC2513-2015-1/syllabus#28]
Hola,

Estaba viendo como consumir una API y hay varias formas. Hay quienes abren una URI y parsean el JSON (solo GET) -- y de ahí depende -- y otros que usan gemas, como [Faraday](https://github.com/lostisland/faraday), [RestClient](https://github.com/rest-client/rest-client) o [Httparty](https://github.com/jnunemaker/httparty).

¿Qué es lo más recomendable para la entrega (y que está permitido)? Gracias

P.D.: Había olvidado mencionar [ActiveResource](https://github.com/rails/activeresource)

**Comment by lopezjurip** [comment]
De la manera que más fácil les resulte :+1: 
Si es una API simple, quizás la primera opción es la mejor. Si las gemas los ayudan con el manejo de la API key, bien también.

**Comment by jecastro1** [comment]
Vale, muchas gracias
