### ISSUE TITLE
Cancan?

### ISSUE THREAD

**Issue by isseu** [IIC2513-2015-1/syllabus#3]
Se puede utilizar [Cancan](https://github.com/ryanb/cancan)? ... pls
Puedo utilizar bootstrap sin la gema? :)

Gracias!

**Comment by lopezjurip** [comment]
Todavía está en conversación qué gemas usar, dejaré esta Issue abierta hasta tenerlo formalizado con el profe :ok_hand:

**Comment by lopezjurip** [comment]
Se determinó que CanCan se prohibirá :-1:
