### ISSUE TITLE
Dudas enunciado central de eventos

### ISSUE THREAD

**Issue by isseu** [IIC2513-2015-1/syllabus#5]
Hola!, tengo un par de dudas sobre el enunciado del proyecto [Central de Eventos](https://github.com/IIC2513-2015-1/syllabus/blob/master/Proyectos/Central-de-eventos.md).
- ¿Se puede eliminar un lugar? 
- ¿A que se refiere que el organizador de un evento puede configurar su los organizadores pagan o no?

Por ultimo, ¿puedo utilizar la gema [nifty-generators](https://github.com/ryanb/nifty-generators)? Para crear scaffolds solo con ciertas acciones.

**Comment by lopezjurip** [comment]
Se debería poder eliminar un lugar, siempre y cuando sea el dueño quién lo haga.

Bueno los organizadores pueden elegir asistir a un evento que organizan o no. Entonces se puede configurar si ellos pagan al entrar al lugar.

La gema es un poco vieja, si quieres usarla está bien :+1: (siempre y cuando no genere la authentication)
