### ISSUE TITLE
Fotos

### ISSUE THREAD

**Issue by gerinelda** [IIC2513-2015-1/syllabus#6]
Las imágenes de usuarios o de organizadores (por ejemplo fotos de perfil) deberíamos guardarlas en la base de datos? si no es así, dónde?

Saludos

**Comment by lopezjurip** [comment]
**No es necesario para la primera entrega**. No te preocupes.

Lo que se deberá hacer para ese entonces es usar la gema `paperclip` y bueno, guardarlos en tu misma app, en Dropbox o en un servicio de nube como Microsoft Azure o Amazon S3.  Pero reitero, en otra entrega se pedirá eso :smile:

**Comment by isseu** [comment]
ojo que heroku [no permite escribir en el sistema de  archivos](http://stackoverflow.com/questions/5096588/paperclipped-on-heroku). Se puede también guardar en la base de datos, pero no es recomendable.
