### ISSUE TITLE
Scaffold: destroy y create -> relación duplicada

### ISSUE THREAD

**Issue by FranLucchini** [IIC2513-2015-1/syllabus#7]
Saludos, tengo una tabla que deseo botar y crearla de nuevo. Destruyo y luego vuelvo a crear el scaffold. El problema es al hacer 

``` ruby
rake db:migrate
```

dice que estoy intentando de crear una tabla que ya existe... Intenté usar:

``` ruby
rails ActiveRecord::Migration.drop_table(:events)
```

pero tampoco me funcionó.

**Comment by lopezjurip** [comment]
Podrías hacer `rake db:rollback`, modificar la tabla `events` y volver a migrar con `rake db:migrate`.

Otra opción es hacer una migración que bote la tabla: http://stackoverflow.com/questions/4020131/rails-db-migration-how-to-drop-a-table

Si el problema es feo, la última opción es botar toda la base de datos con:

``` ruby
rake db:drop db:create
```

Y revisar si están bien hechas las migraciones. Esto no es muy recomendable para futuro porque puede destruir el esquema que tengan los demás colaboradores y el esquema de la app en producción... pero como están recién partiendo con la app, esto es aceptable.

**Comment by FranLucchini** [comment]
Igual me gustaría saber qué puedo haber hecho mal...

Si de algo sirve, agrego las primeras lineas del error:

== 20150407234427 CreateEvents: migrating =====================================
-- create_table(:events)

Por lo que entiendo, esto va a la migracion e intenta crear de nuevo la tabla, no?

**Comment by lopezjurip** [comment]
Claro, eso intenta crear la tabla. 

No sé qué pudo salir mal.

**Comment by FranLucchini** [comment]
Pucha... gracias igual.

Última pregunta, cada vez que quiera hacer una migración no es necesario hacer un rollback, cierto?

**Comment by FranLucchini** [comment]
Ya lo arreglé! Estaba usando mal :

``` ruby
rails ActiveRecord::Migration.drop_table(:events)
```

Tenía que hacer:

``` ruby
$ rails console
>> ActiveRecord::Migration.drop_table(:events)
```
