### ISSUE TITLE
Asociación unidireccional

### ISSUE THREAD

**Issue by vdrg** [IIC2513-2015-1/syllabus#8]
Hola!, una duda, si tuviese un modelo "Cosa" y quisiera que existan varios tipos de Cosas (otro modelo CosaType) como debería relacionarlos? CosaType no debería tener ninguna referencia a la tabla cosas, sólo Cosa debería tener referencia a su tipo.

Gracias

**Comment by lopezjurip** [comment]
Estás hablando de herencia?

**Comment by vdrg** [comment]
Noo, a ver, otro ejemplo: Tengo el modelo Polera, y quisiera que cada polera tenga uno o más Colores. Puedo tener muchos colores, y cada Polera debería tener almacenado su(s) color(es), pero Color no debería tener en su tabla una referencia a alguna polera.. se entiende??

Si fuese programación orientada a objetos sería más o menos como que la clase Polera tenga un atributo Color. Un Color no tiene que saber nada de las poleras que lo contienen.

Lo que quiero es parecido a has_and_belongs_to_many (volviendo al ej. anterior: que se cree una nueva tabla que contiene el id de Polera y el id de Color) pero si no me equivoco con has_and_belongs_to_many hay una asociación bidireccional.. ¿se puede poner una asociación has_and_belongs_to_many en sólo uno de los modelos?

Gracias!

**Comment by lopezjurip** [comment]
Necesitas una **join table**, pues es una relación de _n_ a _n_. 
Una opción es usar la relación `has_and_belongs_to_many`.

Quedaría así:

``` ruby
class Shirt
  has_and_belongs_to_many :colors
end

class Color
  # Opcional, según lo que quieres 
  has_and_belongs_to_many :shirts
end
```

Necesitarás una migración, te recomiendo ver: http://guides.rubyonrails.org/association_basics.html#the-has-and-belongs-to-many-association

**Comment by vdrg** [comment]
Si lei eso, pero en ese caso puedo acceder desde Color a Shirt o no?

**Comment by lopezjurip** [comment]
Para que no tengas problemas, la convención es que la join table se llame: `colors_shirts`. Antes del `_` va el modelo con **menor** índice alfabético (_c_ < _s_) y ambos en plural

``` ruby
create_table :colors_shirts, id: false do |t|  # se usa id: false para evitar que esta tabla tenga id's para cada row
    t.belongs_to :color, index: true
    t.belongs_to :shirt, index: true
end
```

**Comment by vdrg** [comment]
Ahh no, pensé que era obligación poner el has_and_belongs_to_many en ambos modelos! Gracias!
