### ISSUE TITLE
rails g scaffold clasehija --parent clasepadre (esto es herencia, no?)

### ISSUE THREAD

**Issue by viperalta** [IIC2513-2015-1/syllabus#9]
Es necesario hacer un scaffold de la clase padre? o es mejor práctica hacer scaffold de las diferentes clases hijas y solo un model de la case padre?

**Comment by lopezjurip** [comment]
Sí, **es herencia**, en específico es STI (Single Table Inheritance).
Sí, tienes que hacer el scaffold del padre. 

Ojo que **no siempre es recomendable** usar herencia. 
- Si la _superclase_ y las _clases derivadas_ tienen **pocos** atributos distintos y tienen comportamientos distintos, entonces sí es bueno usar herencia.
- Si la _superclase_ y las _clases derivadas_ tienen **muchos** atributos distintos entre ellos, entonces es mejor hacer clases por separado. 
  - En Ruby existe el [duck typing](http://en.wikipedia.org/wiki/Duck_typing) así que no hay problema con esto. 
  - Puedes usar _[Concerns](http://api.rubyonrails.org/classes/ActiveSupport/Concern.html)_ para reutilizar código, recuerda [DRY](http://en.wikipedia.org/wiki/Don%27t_repeat_yourself) :+1: 

---

UPDATE:
STI implica que se usará una única tabla en tu base de datos para la superclase y subclases, si las subclases son muy variadas te quedará una tabla con demasiadas columnas

**Comment by viperalta** [comment]
Valee!!! 👍🏿👍🏾👍🏽
